### ISSUE TITLE
Plugins and commands

### ISSUE THREAD

**Issue by henrikcoll** [Blue-DiscordBot/Blue#1]
We need commands, and to keep organized we split functionality into plugins.
We also need:

- [X] Plugin loader. #2
- [X] Plugin template. #2
- [X] Command handler. #2
- [X] A way to download, list and remove plugins. #4 
- [X] Plugin update notifications. #4 
- [x] Check to see if user has permission to run the command. #3 
- [x] Help command to help users with commands #3
